import { PDFDocument, StandardFonts, rgb, type PDFPage } from 'pdf-lib';
import { readFileSync } from 'fs';
import path from 'path';

// Remi green — matching the catalogue section-band colour so the
// padded pages don't look like foreign insertions.
const BRAND_GREEN = rgb(0x1f / 255, 0x4a / 255, 0x3a / 255);
const LINE_GREY = rgb(0.78, 0.78, 0.78);
const FOOTER_GREY = rgb(0.55, 0.55, 0.55);

function drawNotesPage(
  page: PDFPage,
  opts: {
    width: number;
    height: number;
    titleFont: Awaited<ReturnType<PDFDocument['embedFont']>>;
    footerFont: Awaited<ReturnType<PDFDocument['embedFont']>>;
  },
) {
  const { width, height, titleFont, footerFont } = opts;
  const PAGE_MARGIN_X = 24;
  const TOP_MARGIN = 32;
  const BOTTOM_MARGIN = 32;
  const TITLE_SIZE = 14;
  const LINE_SPACING = 22;

  const title = 'NOTES';
  const titleWidth = titleFont.widthOfTextAtSize(title, TITLE_SIZE);
  const titleY = height - TOP_MARGIN - TITLE_SIZE;
  page.drawText(title, {
    x: (width - titleWidth) / 2,
    y: titleY,
    size: TITLE_SIZE,
    font: titleFont,
    color: BRAND_GREEN,
  });

  const ruleWidth = 36;
  const ruleY = titleY - 6;
  page.drawLine({
    start: { x: (width - ruleWidth) / 2, y: ruleY },
    end: { x: (width + ruleWidth) / 2, y: ruleY },
    thickness: 0.8,
    color: BRAND_GREEN,
  });

  const firstLineY = ruleY - 28;
  const lastLineY = BOTTOM_MARGIN + 16;
  for (let y = firstLineY; y >= lastLineY; y -= LINE_SPACING) {
    page.drawLine({
      start: { x: PAGE_MARGIN_X, y },
      end: { x: width - PAGE_MARGIN_X, y },
      thickness: 0.4,
      color: LINE_GREY,
    });
  }

  const footerText = 'Notes  ·  Generated by Remi';
  const footerSize = 7;
  const footerWidth = footerFont.widthOfTextAtSize(footerText, footerSize);
  page.drawText(footerText, {
    x: (width - footerWidth) / 2,
    y: 16,
    size: footerSize,
    font: footerFont,
    color: FOOTER_GREY,
  });
}

// Cache the back-cover JPEG at module load — it's identical on every
// render so there's no point re-reading it from disk each time.
let backCoverBytes: Uint8Array | null = null;
function loadBackCover(): Uint8Array | null {
  if (backCoverBytes !== null) return backCoverBytes;
  try {
    const p = path.join(process.cwd(), 'public', 'branding', 'remi-back-cover.jpg');
    backCoverBytes = readFileSync(p);
    return backCoverBytes;
  } catch {
    return null;
  }
}

async function drawBackCoverPage(
  doc: PDFDocument,
  page: PDFPage,
  opts: { width: number; height: number },
) {
  const { width, height } = opts;
  const bytes = loadBackCover();
  if (!bytes) {
    // If the asset is missing for any reason, fall back to a plain
    // branded page so the booklet page count stays correct.
    page.drawRectangle({ x: 0, y: 0, width, height, color: BRAND_GREEN });
    return;
  }
  const jpg = await doc.embedJpg(bytes);
  // Full-bleed fit. The marketing creative is landscape (~1.5:1);
  // letterbox above/below on A5 portrait with brand-green fill so
  // the page reads as a deliberate back cover rather than a scaled
  // image surrounded by white.
  const imgRatio = jpg.width / jpg.height;
  const imgDrawWidth = width;
  const imgDrawHeight = imgDrawWidth / imgRatio;
  const imgY = (height - imgDrawHeight) / 2;

  page.drawRectangle({ x: 0, y: 0, width, height, color: BRAND_GREEN });
  page.drawImage(jpg, {
    x: 0,
    y: imgY,
    width: imgDrawWidth,
    height: imgDrawHeight,
  });
}

/**
 * Pad a PDF buffer so its page count is a multiple of the given
 * modulus. Saddle-stitched booklets (Mixam et al.) fold A4 sheets
 * in half → 4 pages per physical sheet, so the PDF's page count
 * MUST be a multiple of 4 or the printer will reject it.
 *
 * Rather than appending blank pages, the padding is put to use:
 *   - The final padded page is a Remi-branded back cover (when the
 *     back-cover JPEG is present).
 *   - Any padding pages BEFORE the back cover are ruled Notes pages
 *     for handwritten placements / critiques.
 *
 * Returns a new Uint8Array; the input is not mutated.
 */
export async function padPdfToMultiple(
  input: Uint8Array | Buffer,
  modulus = 4,
): Promise<Uint8Array> {
  const doc = await PDFDocument.load(input);
  const currentPages = doc.getPageCount();
  const target = Math.ceil(currentPages / modulus) * modulus;
  const pagesToAdd = target - currentPages;

  if (pagesToAdd === 0) {
    return doc.save();
  }

  const lastPage = doc.getPage(currentPages - 1);
  const { width, height } = lastPage.getSize();

  const titleFont = await doc.embedFont(StandardFonts.HelveticaBold);
  const footerFont = await doc.embedFont(StandardFonts.Helvetica);

  for (let i = 0; i < pagesToAdd; i++) {
    const page = doc.addPage([width, height]);
    const isFinalPage = i === pagesToAdd - 1;
    if (isFinalPage) {
      await drawBackCoverPage(doc, page, { width, height });
    } else {
      drawNotesPage(page, { width, height, titleFont, footerFont });
    }
  }

  return doc.save();
}
