import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

/**
 * Pad a PDF buffer so its page count is a multiple of the given
 * modulus. Saddle-stitched booklets (Mixam et al.) fold A4 sheets
 * in half → 4 pages per physical sheet, so the PDF's page count
 * MUST be a multiple of 4 or the printer will reject it.
 *
 * Rather than appending blank pages (which exhibitors stare at),
 * we fill the padding with "Notes" pages: a subtle header + ruled
 * lines so they're actually useful ringside for jotting placements
 * and critiques. Same page size as the preceding content so the
 * booklet binds cleanly.
 *
 * Returns a new Uint8Array; the input is not mutated.
 */
export async function padPdfToMultiple(
  input: Uint8Array | Buffer,
  modulus = 4,
): Promise<Uint8Array> {
  const doc = await PDFDocument.load(input);
  const currentPages = doc.getPageCount();
  const target = Math.ceil(currentPages / modulus) * modulus;
  const pagesToAdd = target - currentPages;

  if (pagesToAdd === 0) {
    return doc.save();
  }

  const lastPage = doc.getPage(currentPages - 1);
  const { width, height } = lastPage.getSize();

  // Embed fonts once — reused across every notes page. Helvetica
  // is a standard PDF font so no asset fetch is needed.
  const titleFont = await doc.embedFont(StandardFonts.HelveticaBold);
  const footerFont = await doc.embedFont(StandardFonts.Helvetica);

  // Page margins picked to match the catalogue's ~22pt horizontal
  // padding so the ruled lines align visually with the body text
  // block above them when readers flip back and forth.
  const PAGE_MARGIN_X = 24;
  const TOP_MARGIN = 32;
  const BOTTOM_MARGIN = 32;
  const TITLE_SIZE = 14;
  const LINE_SPACING = 22; // generous enough for handwriting
  // Remi green — matching the catalogue section-band colour so the
  // Notes header doesn't look like a foreign insertion.
  const BRAND_GREEN = rgb(0x1f / 255, 0x4a / 255, 0x3a / 255);
  const LINE_GREY = rgb(0.78, 0.78, 0.78);
  const FOOTER_GREY = rgb(0.55, 0.55, 0.55);

  for (let i = 0; i < pagesToAdd; i++) {
    const page = doc.addPage([width, height]);

    // Title at top
    const title = 'NOTES';
    const titleWidth = titleFont.widthOfTextAtSize(title, TITLE_SIZE);
    const titleY = height - TOP_MARGIN - TITLE_SIZE;
    page.drawText(title, {
      x: (width - titleWidth) / 2,
      y: titleY,
      size: TITLE_SIZE,
      font: titleFont,
      color: BRAND_GREEN,
    });

    // Short accent rule under the title, centred
    const ruleWidth = 36;
    const ruleY = titleY - 6;
    page.drawLine({
      start: { x: (width - ruleWidth) / 2, y: ruleY },
      end: { x: (width + ruleWidth) / 2, y: ruleY },
      thickness: 0.8,
      color: BRAND_GREEN,
    });

    // Ruled lines filling the rest of the page
    const firstLineY = ruleY - 28;
    const lastLineY = BOTTOM_MARGIN + 16;
    for (let y = firstLineY; y >= lastLineY; y -= LINE_SPACING) {
      page.drawLine({
        start: { x: PAGE_MARGIN_X, y },
        end: { x: width - PAGE_MARGIN_X, y },
        thickness: 0.4,
        color: LINE_GREY,
      });
    }

    // Footer — keeps parity with the rest of the catalogue which
    // also footers every page. "Generated by Remi" identifies
    // these padded pages as ours, not a printer insert.
    const footerText = 'Notes  ·  Generated by Remi';
    const footerSize = 7;
    const footerWidth = footerFont.widthOfTextAtSize(footerText, footerSize);
    page.drawText(footerText, {
      x: (width - footerWidth) / 2,
      y: 16,
      size: footerSize,
      font: footerFont,
      color: FOOTER_GREY,
    });
  }

  return doc.save();
}
