import { Document, Page, View, Text } from '@react-pdf/renderer';
import { styles } from './catalogue-styles';
import { CatalogueHeader } from './catalogue-header';
import type { CatalogueEntry, CatalogueShowInfo } from './catalogue-standard';

interface Props {
  show: CatalogueShowInfo;
  entries: CatalogueEntry[];
}

export function CatalogueAbsentees({ show, entries }: Props) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <CatalogueHeader
          showName={show.name}
          organisationName={show.organisation}
          date={show.date}
          venue={show.venue}
          kcLicenceNo={show.kcLicenceNo ?? undefined}
          logoUrl={show.logoUrl}
          subtitle="Absentee List"
        />

        {entries.length === 0 ? (
          <Text style={{ textAlign: 'center', marginTop: 40, fontSize: 11 }}>
            No absentees recorded.
          </Text>
        ) : (
          <View>
            <View style={[styles.absenteeRow, { borderBottomWidth: 1, borderBottomColor: '#000' }]}>
              <Text style={[styles.entryDetail, { fontWeight: 'bold', width: '10%' }]}>
                Cat. No.
              </Text>
              <Text style={[styles.entryDetail, { fontWeight: 'bold', width: '30%' }]}>
                Dog
              </Text>
              <Text style={[styles.entryDetail, { fontWeight: 'bold', width: '25%' }]}>
                Breed
              </Text>
              <Text style={[styles.entryDetail, { fontWeight: 'bold', width: '20%' }]}>
                Exhibitor
              </Text>
              <Text style={[styles.entryDetail, { fontWeight: 'bold', width: '15%' }]}>
                Classes
              </Text>
            </View>

            {entries.map((entry) => (
              <View key={entry.catalogueNumber} style={styles.absenteeRow}>
                <Text style={[styles.entryDetail, { width: '10%' }]}>
                  {entry.catalogueNumber ?? '—'}
                </Text>
                <Text style={[styles.entryDetail, { width: '30%' }]}>
                  {entry.dogName ?? '—'}
                </Text>
                <Text style={[styles.entryDetail, { width: '25%' }]}>
                  {entry.breed ?? '—'}
                </Text>
                <Text style={[styles.entryDetail, { width: '20%' }]}>
                  {entry.exhibitor ?? '—'}
                </Text>
                <Text style={[styles.entryDetail, { width: '15%' }]}>
                  {entry.classes
                    .map((c) => c.name)
                    .filter(Boolean)
                    .join(', ')}
                </Text>
              </View>
            ))}

            <Text style={{ marginTop: 16, fontSize: 9, fontWeight: 'bold' }}>
              Total Absentees: {entries.length}
            </Text>
          </View>
        )}

        <Text
          style={styles.footer}
          render={({ pageNumber, totalPages }) =>
            `Page ${pageNumber} of ${totalPages} — Absentee List — Generated by Remi`
          }
          fixed
        />
      </Page>
    </Document>
  );
}
