import { Document, Page, View, Text } from '@react-pdf/renderer';
import { styles } from './catalogue-styles';
import { CatalogueHeader } from './catalogue-header';
import type { CatalogueEntry, CatalogueShowInfo } from './catalogue-standard';

interface Props {
  show: CatalogueShowInfo;
  entries: CatalogueEntry[];
}

function formatDob(dob: string | null | undefined) {
  if (!dob) return '';
  return new Date(dob).toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
  });
}

// Group entries alphabetically by first letter of dog name
function groupAlphabetically(entries: CatalogueEntry[]) {
  const sorted = [...entries].sort((a, b) =>
    (a.dogName ?? '').localeCompare(b.dogName ?? '')
  );

  const groups: Record<string, CatalogueEntry[]> = {};
  for (const entry of sorted) {
    const letter = (entry.dogName ?? '?').charAt(0).toUpperCase();
    groups[letter] ??= [];
    groups[letter].push(entry);
  }

  return groups;
}

export function CatalogueAlphabetical({ show, entries }: Props) {
  const grouped = groupAlphabetically(entries);
  const letters = Object.keys(grouped).sort();

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <CatalogueHeader
          showName={show.name}
          organisationName={show.organisation}
          date={show.date}
          venue={show.venue}
          kcLicenceNo={show.kcLicenceNo ?? undefined}
          logoUrl={show.logoUrl}
          subtitle="Catalogue — Alphabetical Index"
        />

        {letters.map((letter) => (
          <View key={letter}>
            <Text style={styles.groupHeading}>{letter}</Text>

            {grouped[letter].map((entry) => (
              <View key={entry.catalogueNumber} style={styles.entryRow}>
                <View style={{ flexDirection: 'row', gap: 8 }}>
                  <Text style={styles.catalogueNumber}>
                    {entry.catalogueNumber ?? '—'}
                  </Text>
                  <Text style={styles.dogName}>
                    {entry.dogName ?? 'Unnamed'}
                  </Text>
                </View>

                <Text style={styles.entryDetail}>
                  {entry.breed ?? ''}
                  {entry.sex ? ` (${entry.sex === 'dog' ? 'Dog' : 'Bitch'})` : ''}
                  {entry.dateOfBirth ? ` — D.O.B: ${formatDob(entry.dateOfBirth)}` : ''}
                </Text>

                {entry.sire && (
                  <Text style={styles.entryDetail}>Sire: {entry.sire}</Text>
                )}
                {entry.dam && (
                  <Text style={styles.entryDetail}>Dam: {entry.dam}</Text>
                )}
                {entry.breeder && (
                  <Text style={styles.entryDetail}>Breeder: {entry.breeder}</Text>
                )}

                {entry.owners.length > 0 && (
                  <Text style={styles.entryDetail}>
                    Owner{entry.owners.length > 1 ? 's' : ''}:{' '}
                    {entry.owners.map((o) => o.name).join(' & ')}
                  </Text>
                )}

                {entry.classes.length > 0 && (
                  <Text style={styles.entryClasses}>
                    Entered in:{' '}
                    {entry.classes
                      .map((c) => c.name)
                      .filter(Boolean)
                      .join(', ')}
                  </Text>
                )}
              </View>
            ))}
          </View>
        ))}

        <Text
          style={styles.footer}
          render={({ pageNumber, totalPages }) =>
            `Page ${pageNumber} of ${totalPages} — Generated by Remi`
          }
          fixed
        />
      </Page>
    </Document>
  );
}
