import { Document, Page, View, Text } from '@react-pdf/renderer';
import { styles } from './catalogue-styles';
import { CatalogueHeader } from './catalogue-header';
import type { CatalogueEntry, CatalogueShowInfo } from './catalogue-standard';

interface Props {
  show: CatalogueShowInfo;
  entries: CatalogueEntry[];
}

function formatDob(dob: string | null | undefined) {
  if (!dob) return '';
  return new Date(dob).toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
  });
}

// Group entries by class, preserving sort metadata
function groupByClass(entries: CatalogueEntry[]) {
  const classes: Record<string, {
    sex: string | null | undefined;
    classNumber: number | null | undefined;
    sortOrder: number | undefined;
    entries: CatalogueEntry[];
  }> = {};

  for (const entry of entries) {
    for (const cls of entry.classes) {
      const className = cls.name ?? 'Unknown Class';
      classes[className] ??= {
        sex: cls.sex,
        classNumber: cls.classNumber,
        sortOrder: cls.sortOrder,
        entries: [],
      };
      classes[className].entries.push(entry);
    }
  }

  return classes;
}

export function CatalogueByClass({ show, entries }: Props) {
  const grouped = groupByClass(entries);
  // Sort by classNumber if assigned, otherwise by sortOrder, then alphabetically
  const classNames = Object.keys(grouped).sort((a, b) => {
    const aNum = grouped[a].classNumber;
    const bNum = grouped[b].classNumber;
    if (aNum != null && bNum != null) return aNum - bNum;
    if (aNum != null) return -1;
    if (bNum != null) return 1;
    const aSort = grouped[a].sortOrder ?? 0;
    const bSort = grouped[b].sortOrder ?? 0;
    if (aSort !== bSort) return aSort - bSort;
    return a.localeCompare(b);
  });

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <CatalogueHeader
          showName={show.name}
          organisationName={show.organisation}
          date={show.date}
          venue={show.venue}
          kcLicenceNo={show.kcLicenceNo ?? undefined}
          logoUrl={show.logoUrl}
          subtitle="Catalogue — By Class"
        />

        {classNames.map((className) => {
          const { sex, classNumber, entries: classEntries } = grouped[className];
          const sorted = [...classEntries].sort(
            (a, b) => (a.catalogueNumber ?? '').localeCompare(b.catalogueNumber ?? '', undefined, { numeric: true })
          );

          return (
            <View key={className}>
              <View style={{ flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', ...styles.groupHeading }}>
                <Text>{classNumber ? `Class ${classNumber}: ${className}` : className}</Text>
                {sex && (
                  <Text style={{ fontSize: 9, fontStyle: 'italic' }}>
                    ({sex === 'dog' ? 'Dogs' : sex === 'bitch' ? 'Bitches' : 'Open'})
                  </Text>
                )}
              </View>
              <Text style={{ fontSize: 8, color: '#666', marginBottom: 6 }}>
                {sorted.length} {sorted.length === 1 ? 'entry' : 'entries'}
              </Text>

              {sorted.map((entry) => (
                <View key={`${className}-${entry.catalogueNumber}`} style={styles.entryRow}>
                  <View style={{ flexDirection: 'row', gap: 8 }}>
                    <Text style={styles.catalogueNumber}>
                      {entry.catalogueNumber ?? '—'}
                    </Text>
                    <Text style={styles.dogName}>
                      {entry.dogName ?? 'Unnamed'}
                    </Text>
                  </View>
                  <Text style={styles.entryDetail}>
                    {entry.breed ?? ''}
                    {entry.dateOfBirth ? ` — D.O.B: ${formatDob(entry.dateOfBirth)}` : ''}
                  </Text>
                  {entry.owners.length > 0 && (
                    <Text style={styles.entryDetail}>
                      Owner{entry.owners.length > 1 ? 's' : ''}:{' '}
                      {entry.owners.map((o) => o.name).join(' & ')}
                    </Text>
                  )}
                </View>
              ))}
            </View>
          );
        })}

        <Text
          style={styles.footer}
          render={({ pageNumber, totalPages }) =>
            `Page ${pageNumber} of ${totalPages} — Generated by Remi`
          }
          fixed
        />
      </Page>
    </Document>
  );
}
