import { Page, View, Text, Image } from '@react-pdf/renderer';
import { styles } from './catalogue-styles';
import type { CatalogueShowInfo } from './catalogue-standard';

const SHOW_TYPE_LABELS: Record<string, string> = {
  championship: 'Championship Show',
  premier_open: 'Premier Open Show',
  open: 'Open Show',
  limited: 'Limited Show',
  primary: 'Primary Show',
  companion: 'Companion Show',
};

function formatCoverDate(dateStr: string): string {
  const d = new Date(dateStr);
  const day = String(d.getDate()).padStart(2, '0');
  const month = String(d.getMonth() + 1).padStart(2, '0');
  const year = d.getFullYear();
  return `${day}.${month}.${year}`;
}

interface FrontMatterProps {
  show: CatalogueShowInfo;
}

/** Cover page for the KC standard catalogue */
export function CoverPage({ show }: FrontMatterProps) {
  const showTypeLabel = show.showType ? SHOW_TYPE_LABELS[show.showType] : undefined;

  return (
    <Page size="A5" style={styles.coverPage}>
      {show.logoUrl && (
        <Image
          src={show.logoUrl}
          style={{ width: 80, height: 80, marginBottom: 20 }}
        />
      )}

      {show.organisation && (
        <Text style={styles.coverOrganisation}>{show.organisation}</Text>
      )}

      <Text style={styles.coverShowName}>{show.name}</Text>

      {showTypeLabel && (
        <Text style={styles.coverSubtitle}>{showTypeLabel}</Text>
      )}

      <Text style={styles.coverRegulatory}>
        held under Royal Kennel Club Rules &amp; Show Regulations F(1)
      </Text>

      <Text style={styles.coverDetail}>{formatCoverDate(show.date)}</Text>

      {show.venue && (
        <Text style={styles.coverDetail}>
          {show.venue}{show.venueAddress ? `, ${show.venueAddress}` : ''}
        </Text>
      )}

      {show.kcLicenceNo && (
        <Text style={{ ...styles.coverDetail, marginTop: 12 }}>
          KC Licence No: {show.kcLicenceNo}
        </Text>
      )}

      {show.secretaryEmail && (
        <Text style={styles.coverDetail}>
          Show Secretary: {show.secretaryEmail}
        </Text>
      )}

      <Text
        style={styles.footer}
        render={({ pageNumber, totalPages }) =>
          `Page ${pageNumber} of ${totalPages}  ·  Generated by Remi`
        }
        fixed
      />
    </Page>
  );
}

/** Judges list page — breed → judge name table */
export function JudgesListPage({ show }: FrontMatterProps) {
  const judges = show.judgesByBreedName ?? {};
  const sortedBreeds = Object.keys(judges).sort();

  if (sortedBreeds.length === 0) return null;

  return (
    <Page size="A5" style={styles.frontMatterPage}>
      <Text style={styles.frontMatterTitle}>List of Judges</Text>

      {/* Table header */}
      <View style={{ ...styles.judgesListRow, borderBottomWidth: 1.5, borderBottomColor: '#000', marginBottom: 4 }}>
        <Text style={{ ...styles.judgesListBreed, fontWeight: 'bold' }}>Breed</Text>
        <Text style={{ ...styles.judgesListJudge, fontWeight: 'bold' }}>Judge</Text>
      </View>

      {sortedBreeds.map((breed) => (
        <View key={breed} style={styles.judgesListRow}>
          <Text style={styles.judgesListBreed}>{breed}</Text>
          <Text style={styles.judgesListJudge}>{judges[breed]}</Text>
        </View>
      ))}

      <Text
        style={styles.footer}
        render={({ pageNumber, totalPages }) =>
          `Page ${pageNumber} of ${totalPages}  ·  Generated by Remi`
        }
        fixed
      />
    </Page>
  );
}

/** Class definitions page — name + description for each class */
export function ClassDefinitionsPage({ show }: FrontMatterProps) {
  const defs = show.classDefinitions ?? [];

  // Only render if we have at least one definition with a description
  const defsWithDesc = defs.filter((d) => d.description);
  if (defsWithDesc.length === 0) return null;

  return (
    <Page size="A5" style={styles.frontMatterPage}>
      <Text style={styles.frontMatterTitle}>Definitions of Classes</Text>

      {defsWithDesc.map((def) => (
        <View key={def.name} wrap={false}>
          <Text style={styles.classDefName}>{def.name}</Text>
          <Text style={styles.classDefDescription}>{def.description}</Text>
        </View>
      ))}

      <Text
        style={styles.footer}
        render={({ pageNumber, totalPages }) =>
          `Page ${pageNumber} of ${totalPages}  ·  Generated by Remi`
        }
        fixed
      />
    </Page>
  );
}
