import { Document, Page, View, Text } from '@react-pdf/renderer';
import { styles } from './catalogue-styles';
import { CatalogueHeader } from './catalogue-header';
import type { CatalogueEntry, CatalogueShowInfo } from './catalogue-standard';
import { formatDobKC, formatPedigreeKC, formatOwnerKC, uppercaseName, formatClassList } from './catalogue-utils';

interface Props {
  show: CatalogueShowInfo;
  entries: CatalogueEntry[];
}

// Group entries alphabetically by first letter of dog name
function groupAlphabetically(entries: CatalogueEntry[]) {
  const sorted = [...entries].sort((a, b) =>
    (a.dogName ?? '').localeCompare(b.dogName ?? '')
  );

  const groups: Record<string, CatalogueEntry[]> = {};
  for (const entry of sorted) {
    const letter = (entry.dogName ?? '?').charAt(0).toUpperCase();
    groups[letter] ??= [];
    groups[letter].push(entry);
  }

  return groups;
}

export function CatalogueAlphabetical({ show, entries }: Props) {
  const grouped = groupAlphabetically(entries);
  const letters = Object.keys(grouped).sort();

  return (
    <Document>
      {/* One <Page> per letter — avoids @react-pdf coordinate overflow on large shows */}
      {letters.map((letter, idx) => (
        <Page key={letter} size="A5" style={styles.page} wrap>
          {/* Header on first page only */}
          {idx === 0 && (
            <CatalogueHeader
              showName={show.name}
              showType={show.showType}
              organisationName={show.organisation}
              date={show.date}
              venue={show.venue}
              venueAddress={show.venueAddress}
              kcLicenceNo={show.kcLicenceNo ?? undefined}
              logoUrl={show.logoUrl}
              subtitle="Catalogue — Alphabetical Index"
            />
          )}

          <Text style={styles.groupHeading}>{letter}</Text>

          {grouped[letter].map((entry) => {
            const pedigree = formatPedigreeKC(entry.sire, entry.dam);
            return (
              <View
                key={entry.catalogueNumber}
                style={styles.entryRowWrap}
                wrap={false}
              >
                <View style={{ flexDirection: 'row', alignItems: 'baseline' }}>
                  <Text style={styles.catalogueNumber}>
                    {entry.catalogueNumber ?? '—'}
                  </Text>
                  <Text style={styles.dogName}>
                    {uppercaseName(entry.dogName) || 'Unnamed'}
                  </Text>
                </View>

                {/* RKC reg + DOB + colour + sex */}
                <Text style={styles.entryDetail}>
                  {[
                    entry.kcRegNumber,
                    entry.breed,
                    entry.sex === 'dog' ? 'Dog' : entry.sex === 'bitch' ? 'Bitch' : null,
                    entry.dateOfBirth ? `D.O.B: ${formatDobKC(entry.dateOfBirth)}` : null,
                    entry.colour,
                  ].filter(Boolean).join('  —  ')}
                </Text>

                {/* Pedigree: By [sire] ex [dam] */}
                {pedigree && (
                  <Text style={styles.entryDetail}>{pedigree}</Text>
                )}

                {/* Breeder */}
                {entry.breeder && (
                  <Text style={styles.entryDetail}>
                    <Text style={styles.entryDetailLabel}>Breeder: </Text>
                    {entry.breeder}
                  </Text>
                )}

                {/* Owner(s) — UPPER CASE + address (or "Exh." if owner is exhibiting) */}
                {entry.owners.length > 0 && (
                  <Text style={styles.entryDetail}>
                    <Text style={styles.entryDetailLabel}>
                      Owner{entry.owners.length > 1 ? 's' : ''}:{' '}
                    </Text>
                    {formatOwnerKC(entry.owners, entry.exhibitorId)}
                  </Text>
                )}

                {entry.classes.length > 0 && (
                  <Text style={styles.entryClasses}>
                    Entered in: {formatClassList(entry.classes)}
                  </Text>
                )}
              </View>
            );
          })}

          <Text
            style={styles.footer}
            render={({ pageNumber, totalPages }) =>
              `Page ${pageNumber} of ${totalPages}  ·  Generated by Remi`
            }
            fixed
          />
        </Page>
      ))}
    </Document>
  );
}
