import { Document, Page, View, Text } from '@react-pdf/renderer';
import { styles } from './catalogue-styles';
import { CatalogueHeader } from './catalogue-header';
import type { CatalogueEntry, CatalogueShowInfo } from './catalogue-standard';
import { uppercaseName } from './catalogue-utils';

interface Props {
  show: CatalogueShowInfo;
  entries: CatalogueEntry[];
}

const colWidths = {
  catNo: '8%',
  dog: '30%',
  breed: '22%',
  sex: '8%',
  exhibitor: '17%',
  classes: '15%',
} as const;

function HeaderCell({ width, children }: { width: string; children: string }) {
  return (
    <Text style={{ fontSize: 8, fontWeight: 'bold', width }}>
      {children}
    </Text>
  );
}

function Cell({ width, children }: { width: string; children: string }) {
  return (
    <Text style={{ fontSize: 8, color: '#333', width }}>
      {children}
    </Text>
  );
}

export function CatalogueAbsentees({ show, entries }: Props) {
  return (
    <Document>
      <Page size="A4" style={styles.page} wrap>
        <CatalogueHeader
          showName={show.name}
          showType={show.showType}
          organisationName={show.organisation}
          date={show.date}
          venue={show.venue}
          venueAddress={show.venueAddress}
          kcLicenceNo={show.kcLicenceNo ?? undefined}
          logoUrl={show.logoUrl}
          subtitle="Absentee List"
        />

        {entries.length === 0 ? (
          <Text style={{ textAlign: 'center', marginTop: 40, fontSize: 11 }}>
            No absentees recorded.
          </Text>
        ) : (
          <View>
            {/* Table header */}
            <View style={styles.absenteeHeaderRow}>
              <HeaderCell width={colWidths.catNo}>Cat.</HeaderCell>
              <HeaderCell width={colWidths.dog}>Dog</HeaderCell>
              <HeaderCell width={colWidths.breed}>Breed</HeaderCell>
              <HeaderCell width={colWidths.sex}>Sex</HeaderCell>
              <HeaderCell width={colWidths.exhibitor}>Exhibitor</HeaderCell>
              <HeaderCell width={colWidths.classes}>Classes</HeaderCell>
            </View>

            {entries.map((entry) => (
              <View key={entry.catalogueNumber} style={styles.absenteeRow} wrap={false}>
                <Cell width={colWidths.catNo}>
                  {entry.catalogueNumber ?? '—'}
                </Cell>
                <Cell width={colWidths.dog}>
                  {uppercaseName(entry.dogName) || '—'}
                </Cell>
                <Cell width={colWidths.breed}>
                  {entry.breed ?? '—'}
                </Cell>
                <Cell width={colWidths.sex}>
                  {entry.sex === 'dog' ? 'D' : entry.sex === 'bitch' ? 'B' : '—'}
                </Cell>
                <Cell width={colWidths.exhibitor}>
                  {entry.exhibitor ?? '—'}
                </Cell>
                <Cell width={colWidths.classes}>
                  {entry.classes
                    .map((c) => c.classNumber ? `${c.classNumber}` : c.name)
                    .filter(Boolean)
                    .join(', ')}
                </Cell>
              </View>
            ))}

            <Text style={{ marginTop: 16, fontSize: 9, fontWeight: 'bold' }}>
              Total Absentees: {entries.length}
            </Text>
          </View>
        )}

        <Text
          style={styles.footer}
          render={({ pageNumber, totalPages }) =>
            `Page ${pageNumber} of ${totalPages}  ·  Absentee List  ·  Generated by Remi`
          }
          fixed
        />
      </Page>
    </Document>
  );
}
