/**
 * pdf-kit/page-frame — a `<Page>` wrapper that standardises size, margins,
 * and fixed header/footer slots (including the folio), generalising the
 * "Page x of y" `fixed` + `render={({ pageNumber, totalPages }) => …}`
 * pattern hand-rolled in 11 files (judge-contract-pdf.tsx,
 * show-schedule(-multibreed).tsx, judges-book.tsx, five catalogue-*.tsx
 * files, show-report-pdf.tsx, sv-results-pdf.tsx, ring-board.tsx).
 *
 * THE FIXED-FOOTER BORDER RULE — read this before touching `footerStyle`:
 *
 * A `fixed` absolute-positioned footer that also carries a `borderTopWidth`
 * has previously shipped a footer rule whose Y coordinate grew geometrically
 * across pages of the same document (a real production bug this kit is
 * designed against). `headerStyle`/`footerStyle` are therefore typed as
 * `NoBorderStyle` — TypeScript rejects a border prop at the call site. If a
 * header/footer needs a rule line, put the border on a NON-fixed child
 * `View` nested one level inside the slot instead (the slot's own `fixed`
 * View stays borderless; a plain child View can carry any style safely):
 *
 *   <PageFrame
 *     footer={<View style={{ borderTopWidth: 0.5, borderTopColor: '#ccc', paddingTop: 4 }}>
 *       <Text>Generated by Remi</Text>
 *     </View>}
 *   />
 */
import React from 'react';
import { Page, View, Text } from '@react-pdf/renderer';
import type { Style, PageSize, Orientation } from '@react-pdf/types';

// The full set of border-related Style keys (see @react-pdf/stylesheet's
// BorderShorthandStyle + BorderExpandedStyle) — hand-listed rather than
// imported from the deeper `@react-pdf/stylesheet` transitive package,
// which (unlike `@react-pdf/types`) isn't something anything in this repo
// imports today.
type BorderKey =
  | 'border'
  | 'borderTop'
  | 'borderRight'
  | 'borderBottom'
  | 'borderLeft'
  | 'borderColor'
  | 'borderRadius'
  | 'borderStyle'
  | 'borderWidth'
  | 'borderTopColor'
  | 'borderTopStyle'
  | 'borderTopWidth'
  | 'borderRightColor'
  | 'borderRightStyle'
  | 'borderRightWidth'
  | 'borderBottomColor'
  | 'borderBottomStyle'
  | 'borderBottomWidth'
  | 'borderLeftColor'
  | 'borderLeftStyle'
  | 'borderLeftWidth'
  | 'borderTopLeftRadius'
  | 'borderTopRightRadius'
  | 'borderBottomRightRadius'
  | 'borderBottomLeftRadius';

/** A react-pdf `Style` with every border property removed — see the
 *  fixed-footer rule above. Use this for anything rendered `fixed`. */
export type NoBorderStyle = Omit<Style, BorderKey>;

export interface PageFrameMargins {
  top?: number | string;
  bottom?: number | string;
  left?: number | string;
  right?: number | string;
}

export type FolioFormat = (pageNumber: number, totalPages: number) => string;

export interface FolioProps {
  /** Defaults to "Page {n} of {total}". */
  format?: FolioFormat;
  style?: NoBorderStyle;
}

const defaultFolioFormat: FolioFormat = (n, total) => `Page ${n} of ${total}`;

function folioRenderer(format: FolioFormat) {
  return ({ pageNumber, totalPages }: { pageNumber: number; totalPages: number }) =>
    format(pageNumber, totalPages);
}

/**
 * Standalone "Page x of y" folio — a `fixed` `<Text>` on its own, for
 * documents not otherwise using `PageFrame`. Do not nest this inside
 * another `fixed` element carrying a border (see the file-level rule); do
 * not add a border directly to `style` either — it's typed `NoBorderStyle`.
 */
export function Folio({ format = defaultFolioFormat, style }: FolioProps) {
  return <Text fixed style={style as Style} render={folioRenderer(format)} />;
}

// Used only inside PageFrame's own footer slot, which is already the
// `fixed` element — this inner text does not need (and must not add) its
// own `fixed` flag.
function FolioInline({ format = defaultFolioFormat, style }: FolioProps) {
  return <Text style={style as Style} render={folioRenderer(format)} />;
}

export interface PageFrameProps {
  size?: PageSize;
  orientation?: Orientation;
  margin?: PageFrameMargins;
  /** Additional page-level style (background colour, base font, etc). */
  style?: Style;
  /** Rendered once per page via `fixed`. See the fixed-footer rule above —
   *  `headerStyle` cannot carry a border; put one on a non-fixed child. */
  header?: React.ReactNode;
  headerStyle?: NoBorderStyle;
  /** Rendered once per page via `fixed`, alongside `folio` if given. See
   *  the fixed-footer rule above. */
  footer?: React.ReactNode;
  footerStyle?: NoBorderStyle;
  /** Convenience: renders a `Folio` inside the footer slot. Pass `true` for
   *  the default "Page x of y", or a `FolioProps` to customise format/style. */
  folio?: boolean | FolioProps;
  wrap?: boolean;
  debug?: boolean;
  children: React.ReactNode;
}

/**
 * A `<Page>` wrapper standardising size/margins/fixed header+footer/folio.
 * Existing hand-rolled pages can adopt this incrementally — it renders a
 * plain `<Page>` underneath, so anything that inspects the render tree
 * (tests, `pdftoppm`) sees the same structure a hand-written `<Page>` would
 * produce.
 */
export function PageFrame({
  size = 'A4',
  orientation,
  margin,
  style,
  header,
  headerStyle,
  footer,
  footerStyle,
  folio,
  wrap,
  debug,
  children,
}: PageFrameProps) {
  const pageStyle: Style = {
    ...(margin?.top !== undefined ? { paddingTop: margin.top } : {}),
    ...(margin?.bottom !== undefined ? { paddingBottom: margin.bottom } : {}),
    ...(margin?.left !== undefined ? { paddingLeft: margin.left } : {}),
    ...(margin?.right !== undefined ? { paddingRight: margin.right } : {}),
    ...style,
  };

  const folioProps: FolioProps | null = folio ? (folio === true ? {} : folio) : null;

  return (
    <Page size={size} orientation={orientation} style={pageStyle} wrap={wrap} debug={debug}>
      {header && (
        <View fixed style={headerStyle as Style}>
          {header}
        </View>
      )}
      {children}
      {(footer || folioProps) && (
        <View fixed style={footerStyle as Style}>
          {footer}
          {folioProps && <FolioInline {...folioProps} />}
        </View>
      )}
    </Page>
  );
}
