/**
 * PROVING THE TEST FAILS (brief requirement — noted here, not left in the
 * tree): changed `folioRenderer` to call `format(pageNumber, pageNumber)`
 * (ignoring the real `totalPages`) — both folio tests failed against the
 * real render ("Page 1 of 1" instead of "Page 1 of 3"/"Page 1 of 2").
 * Restored before committing.
 */
import { describe, it, expect } from 'vitest';
import React from 'react';
import { Document, Page, Text, View, renderToBuffer } from '@react-pdf/renderer';
import { registerPdfKitFonts } from '../fonts';
import { PageFrame, Folio, type NoBorderStyle } from '../page-frame';
import { extractBBoxLayout, pdfFontsReport } from './poppler';

registerPdfKitFonts();

// ── Type-level check (compiled by `tsc`, not executed): `NoBorderStyle`
// must reject border properties — see page-frame.tsx's fixed-footer rule.
// If this stops raising the expected error, the type has regressed and no
// longer protects a fixed footer from the borderTop-growth bug.
function typeCheckNoBorderStyleRejectsBorders() {
  // @ts-expect-error borderTopWidth must not be assignable to NoBorderStyle
  const bad: NoBorderStyle = { borderTopWidth: 1 };
  void bad;
  const ok: NoBorderStyle = { paddingTop: 4, color: '#000' };
  void ok;
}
void typeCheckNoBorderStyleRejectsBorders;

function ManyPagesDoc({ pageCount }: { pageCount: number }) {
  return (
    <Document>
      {Array.from({ length: pageCount }, (_, i) => (
        <PageFrame key={i} folio>
          <Text>{`Content page ${i + 1}`}</Text>
        </PageFrame>
      ))}
    </Document>
  );
}

describe('PageFrame + Folio', () => {
  it('renders the folio "Page x of y" on every page', async () => {
    const buf = await renderToBuffer(<ManyPagesDoc pageCount={3} />);
    const pages = extractBBoxLayout(buf);
    expect(pages).toHaveLength(3);
    for (let i = 0; i < 3; i++) {
      const allText = pages[i].lines.map((l) => l.text).join(' | ');
      expect(allText).toContain(`Page ${i + 1} of 3`);
    }
  });

  it('supports a custom folio format', async () => {
    const buf = await renderToBuffer(
      <Document>
        <PageFrame folio={{ format: (n, total) => `${n} / ${total}` }}>
          <Text>Hello</Text>
        </PageFrame>
      </Document>,
    );
    const pages = extractBBoxLayout(buf);
    const allText = pages[0].lines.map((l) => l.text).join(' | ');
    expect(allText).toContain('1 / 1');
  });

  it('defaults to A4 and honours an explicit A5 size', async () => {
    const buf = await renderToBuffer(
      <Document>
        <PageFrame>
          <Text>A4 page</Text>
        </PageFrame>
        <PageFrame size="A5">
          <Text>A5 page</Text>
        </PageFrame>
      </Document>,
    );
    const pages = extractBBoxLayout(buf);
    expect(pages[0].width).toBeCloseTo(595.28, 1);
    expect(pages[1].width).toBeCloseTo(419.53, 1);
  });

  it('applies margin as page padding', async () => {
    const buf = await renderToBuffer(
      <Document>
        <PageFrame margin={{ top: 100, left: 50 }}>
          <Text>Offset text</Text>
        </PageFrame>
      </Document>,
    );
    const pages = extractBBoxLayout(buf);
    const line = pages[0].lines.find((l) => l.text === 'Offset text');
    expect(line).toBeDefined();
    // Allow a couple points of slack for line-height/ascent metrics.
    expect(line!.xMin).toBeGreaterThanOrEqual(49);
    expect(line!.yMin).toBeGreaterThanOrEqual(99);
  });

  it('renders a header and footer alongside content, all fonts embedded', async () => {
    // Page-level fontFamily set explicitly (as every real pdf-kit document
    // will): react-pdf's own default font (Helvetica) is a base-14 font
    // it never embeds — see src/lib/pdf-pad.ts's BASE14_FONTS writeup —
    // so a Text with no fontFamily anywhere in its ancestry is not this
    // component's bug, it's an unrelated pre-print-pass concern.
    const buf = await renderToBuffer(
      <Document>
        <PageFrame
          style={{ fontFamily: 'Times' }}
          header={<Text>Club Name</Text>}
          footer={<Text>Generated by Remi</Text>}
          folio
        >
          <Text>Body content</Text>
        </PageFrame>
      </Document>,
    );
    const pages = extractBBoxLayout(buf);
    const allText = pages[0].lines.map((l) => l.text).join(' | ');
    expect(allText).toContain('Club Name');
    expect(allText).toContain('Body content');
    expect(allText).toContain('Generated by Remi');
    expect(allText).toContain('Page 1 of 1');

    const fonts = pdfFontsReport(buf);
    expect(fonts.length).toBeGreaterThan(0);
    for (const font of fonts) {
      expect(font.embedded).toBe(true);
    }
  });

  it('a border on a NON-fixed child inside footer still renders fine (the escape hatch for a footer rule line)', async () => {
    const buf = await renderToBuffer(
      <Document>
        <PageFrame
          footer={
            <View style={{ borderTopWidth: 1, borderTopColor: '#000000', paddingTop: 4 }}>
              <Text>Footer with a rule</Text>
            </View>
          }
        >
          <Text>Body</Text>
        </PageFrame>
      </Document>,
    );
    const pages = extractBBoxLayout(buf);
    expect(pages[0].lines.map((l) => l.text)).toContain('Footer with a rule');
  });

  it('standalone Folio renders fixed across pages without a PageFrame', async () => {
    const buf = await renderToBuffer(
      <Document>
        {[0, 1].map((i) => (
          <Page key={i} size="A4">
            <Text>{`Page ${i}`}</Text>
            <Folio />
          </Page>
        ))}
      </Document>,
    );
    const pages = extractBBoxLayout(buf);
    expect(pages[0].lines.map((l) => l.text)).toContain('Page 1 of 2');
    expect(pages[1].lines.map((l) => l.text)).toContain('Page 2 of 2');
  });
});
