import { describe, it, expect } from 'vitest';
import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage } from 'pdf-lib';
import fontkit from '@pdf-lib/fontkit';
import { readFileSync } from 'fs';
import path from 'path';
import {
  runCataloguePreflight,
  type CatalogueSnapshotMeta,
} from '../catalogue-preflight';

/**
 * Fixture PDFs built IN-TEST with pdf-lib — never against prod data (per the
 * brief). Every failing check is proved to actually fail before trusting it
 * passes elsewhere (CLAUDE.md — "prove the test fails").
 */

const A5 = [420, 595] as const;

function baseSnapshot(overrides: Partial<CatalogueSnapshotMeta> = {}): CatalogueSnapshotMeta {
  return {
    showStatus: 'entries_closed',
    entryCloseDate: '2026-08-01T00:00:00.000Z',
    catalogueNumbersLockedAt: '2026-08-02T09:00:00.000Z',
    capturedAt: '2026-08-02T09:05:00.000Z',
    rendererGitSha: 'abc1234',
    expectedNumbers: [1, 2, 3, 4],
    entryNames: [
      { number: 1, name: 'FIDO OF SOMEWHERE' },
      { number: 2, name: 'REX OF ELSEWHERE' },
      { number: 3, name: 'BELLA OF NOWHERE' },
      { number: 4, name: 'ZEUS OF EVERYWHERE' },
    ],
    ...overrides,
  };
}

async function embeddedInterFont(doc: PDFDocument): Promise<PDFFont> {
  doc.registerFontkit(fontkit);
  const bytes = readFileSync(path.join(process.cwd(), 'public', 'fonts', 'inter-regular.ttf'));
  return doc.embedFont(bytes);
}

// Realistic catalogue-entry ink density matters here, not just the text
// content: at 40dpi (the no-blank-pages check's rasterisation resolution),
// a couple of short lines measures indistinguishable from a genuinely blank
// page (empirically ~0.998 white — inside the 0.997 threshold), where a real
// multi-field catalogue record (name/reg/sire/dam/breeder/owner) measures
// ~0.99 white, comfortably clear of it — confirmed against the fixtures
// below before trusting any "non-blank" assertion. The filler fields keep
// every "content" fixture page realistically dense regardless of which
// specific `lines` a test needs findable by a given check.
const DENSITY_FILLER = [
  'Reg No: ABC123456  Microchip: 980000123456789',
  'Sire: Champion Sire Dog Of Somewhere',
  'Dam: Champion Dam Dog Of Elsewhere',
  'Breeder: The Breeder Person',
  '4 The Lane, Trowbridge, Wiltshire, BA14 1AA',
];

function drawEntryPage(page: PDFPage, font: PDFFont, lines: string[]): void {
  let y = 550;
  for (const line of [...lines, ...DENSITY_FILLER]) {
    page.drawText(line, { x: 30, y, size: 10, font });
    y -= 16;
  }
}

/** A well-formed 4-page catalogue: embedded-font text on every page, one
 *  entry name per page, matching `baseSnapshot()`'s entryNames/expectedNumbers. */
async function buildWellFormedFixture(): Promise<Buffer> {
  const doc = await PDFDocument.create();
  const font = await embeddedInterFont(doc);
  const names = ['1  FIDO OF SOMEWHERE', '2  REX OF ELSEWHERE', '3  BELLA OF NOWHERE', '4  ZEUS OF EVERYWHERE'];
  for (const line of names) {
    const page = doc.addPage(A5 as unknown as [number, number]);
    drawEntryPage(page, font, [line, 'Owner: J Smith, 4 The Lane, Trowbridge', 'Sire: Some Dog  Dam: Some Bitch']);
  }
  return Buffer.from(await doc.save());
}

async function buildFixture(pageCount: number, opts: { blankPageIndex?: number; useBase14?: boolean } = {}): Promise<Buffer> {
  const doc = await PDFDocument.create();
  const font = opts.useBase14 ? await doc.embedFont(StandardFonts.Helvetica) : await embeddedInterFont(doc);
  for (let i = 0; i < pageCount; i++) {
    const page = doc.addPage(A5 as unknown as [number, number]);
    if (i === opts.blankPageIndex) continue; // truly nothing drawn
    drawEntryPage(page, font, [`${i + 1}  DOG NUMBER ${i + 1}`, 'Owner: Someone, Somewhere']);
  }
  return Buffer.from(await doc.save());
}

/** A ruled "Notes"-style padding page, matching pdf-pad.ts's drawNotesPage —
 *  real content, must NOT be flagged blank even though it's mostly white. */
async function buildFixtureWithNotesPage(): Promise<Buffer> {
  const doc = await PDFDocument.create();
  const font = await embeddedInterFont(doc);
  const entryPage = doc.addPage(A5 as unknown as [number, number]);
  drawEntryPage(entryPage, font, ['1  FIDO OF SOMEWHERE', 'Owner: J Smith, 4 The Lane']);

  const [width, height] = A5;
  const notesPage = doc.addPage(A5 as unknown as [number, number]);
  const titleY = height - 32 - 14;
  notesPage.drawText('NOTES', { x: (width - 40) / 2, y: titleY, size: 14, font, color: rgb(0.12, 0.29, 0.23) });
  notesPage.drawLine({
    start: { x: (width - 36) / 2, y: titleY - 6 },
    end: { x: (width + 36) / 2, y: titleY - 6 },
    thickness: 0.8,
    color: rgb(0.12, 0.29, 0.23),
  });
  let ly = titleY - 6 - 28;
  const lastLineY = 32 + 16;
  while (ly >= lastLineY) {
    notesPage.drawLine({ start: { x: 24, y: ly }, end: { x: width - 24, y: ly }, thickness: 0.4, color: rgb(0.78, 0.78, 0.78) });
    ly -= 22;
  }
  notesPage.drawText('Notes  ·  Generated by Remi', { x: (width - 100) / 2, y: 16, size: 7, font, color: rgb(0.55, 0.55, 0.55) });

  const p3 = doc.addPage(A5 as unknown as [number, number]);
  drawEntryPage(p3, font, ['2  REX OF ELSEWHERE', 'Owner: A Jones, Elsewhere']);
  const p4 = doc.addPage(A5 as unknown as [number, number]);
  drawEntryPage(p4, font, ['3  BELLA OF NOWHERE', 'Owner: B King, Nowhere']);

  return Buffer.from(await doc.save());
}

/** A 4-page steward/by-class-style fixture: competing dogs #1-4 are drawn
 *  (one per page, grouped-by-class style — no NotForCompetitionPage), and
 *  #5 is an NFC entry that consumes a catalogue number but is deliberately
 *  NOT drawn anywhere — real behaviour for judging/by-class(wusv)/marked. */
async function buildFixtureWithUndrawnNfc(): Promise<Buffer> {
  return buildFixture(4);
}

function nfcSnapshot(overrides: Partial<CatalogueSnapshotMeta> = {}): CatalogueSnapshotMeta {
  return baseSnapshot({
    expectedNumbers: [1, 2, 3, 4, 5],
    entryNames: [
      { number: 1, name: 'DOG NUMBER 1' },
      { number: 2, name: 'DOG NUMBER 2' },
      { number: 3, name: 'DOG NUMBER 3' },
      { number: 4, name: 'DOG NUMBER 4' },
      { number: 5, name: 'GHOST NFC DOG', isNfc: true },
    ],
    ...overrides,
  });
}

/** Two text objects drawn in the SAME content-stream order they logically
 *  read in ("41 AMIRA VOM" then its wrapped continuation), but positioned
 *  as if in a two-column layout — a second entry ("42 OTHER DOG") sits at
 *  the SAME y as the first line, one column over. `-layout` mode reads
 *  left-to-right by y-position and interleaves the columns; `-raw` mode
 *  (content-stream order) keeps the wrapped name contiguous. */
async function buildTwoColumnWrapFixture(): Promise<Buffer> {
  const doc = await PDFDocument.create();
  const font = await embeddedInterFont(doc);
  const page = doc.addPage(A5 as unknown as [number, number]);
  const y = 500;
  page.drawText('41  AMIRA VOM', { x: 30, y, size: 10, font });
  page.drawText('FICHTENSCHLAG (IMP DEU)', { x: 30, y: y - 14, size: 10, font });
  page.drawText('42  OTHER DOG', { x: 220, y, size: 10, font });
  let fy = y - 40;
  for (const line of DENSITY_FILLER) {
    page.drawText(line, { x: 30, y: fy, size: 10, font });
    fy -= 16;
  }
  return Buffer.from(await doc.save());
}

describe('runCataloguePreflight', () => {
  it('passes every check on a well-formed 4-page embedded-font catalogue', async () => {
    const pdf = await buildWellFormedFixture();
    const report = await runCataloguePreflight(pdf, baseSnapshot(), { format: 'standard' });

    expect(report.artefact.pages).toBe(4);
    expect(report.artefact.bytes).toBe(pdf.length);
    expect(report.artefact.sha256).toMatch(/^[0-9a-f]{64}$/);
    expect(report.passed).toBe(true);
    for (const check of report.checks) {
      if (check.level === 'fail') expect(check.passed, `${check.id}: ${check.detail}`).toBe(true);
    }
  });

  describe('post-close-snapshot', () => {
    it('fails when captured before entry close', async () => {
      const pdf = await buildWellFormedFixture();
      const report = await runCataloguePreflight(
        pdf,
        baseSnapshot({ capturedAt: '2026-07-31T00:00:00.000Z', entryCloseDate: '2026-08-01T00:00:00.000Z' }),
        { format: 'standard' },
      );
      const check = report.checks.find((c) => c.id === 'post-close-snapshot')!;
      expect(check.level).toBe('fail');
      expect(check.passed).toBe(false);
      expect(report.passed).toBe(false);
    });

    it('fails when show status is not post-close', async () => {
      const pdf = await buildWellFormedFixture();
      const report = await runCataloguePreflight(pdf, baseSnapshot({ showStatus: 'open' }), { format: 'standard' });
      const check = report.checks.find((c) => c.id === 'post-close-snapshot')!;
      expect(check.passed).toBe(false);
    });

    it('warns (not fails) when there is no entry close date', async () => {
      const pdf = await buildWellFormedFixture();
      const report = await runCataloguePreflight(pdf, baseSnapshot({ entryCloseDate: null }), { format: 'standard' });
      const check = report.checks.find((c) => c.id === 'post-close-snapshot')!;
      expect(check.level).toBe('warn');
      expect(check.passed).toBe(true);
      expect(check.detail.toLowerCase()).toContain('no entry close date');
    });
  });

  describe('catalogue-number-completeness', () => {
    it('fails when expectedNumbers has a gap', async () => {
      const pdf = await buildWellFormedFixture();
      const report = await runCataloguePreflight(pdf, baseSnapshot({ expectedNumbers: [1, 2, 4] }), { format: 'standard' });
      const check = report.checks.find((c) => c.id === 'catalogue-number-completeness')!;
      expect(check.passed).toBe(false);
      expect(check.detail).toMatch(/gap/i);
    });

    it('fails when expectedNumbers has a duplicate', async () => {
      const pdf = await buildWellFormedFixture();
      const report = await runCataloguePreflight(pdf, baseSnapshot({ expectedNumbers: [1, 2, 2, 3] }), { format: 'standard' });
      const check = report.checks.find((c) => c.id === 'catalogue-number-completeness')!;
      expect(check.passed).toBe(false);
      expect(check.detail).toMatch(/duplicate/i);
    });

    it('fails when an entry name is missing from the rendered text', async () => {
      const pdf = await buildWellFormedFixture();
      const report = await runCataloguePreflight(
        pdf,
        baseSnapshot({ entryNames: [...baseSnapshot().entryNames, { number: 5, name: 'GHOST DOG NOT IN PDF' }], expectedNumbers: [1, 2, 3, 4, 5] }),
        { format: 'standard' },
      );
      const check = report.checks.find((c) => c.id === 'catalogue-number-completeness')!;
      expect(check.passed).toBe(false);
      expect(check.detail).toContain('GHOST DOG NOT IN PDF');
    });

    it('passes when numbers are gapless and every name is present', async () => {
      const pdf = await buildWellFormedFixture();
      const report = await runCataloguePreflight(pdf, baseSnapshot(), { format: 'standard' });
      const check = report.checks.find((c) => c.id === 'catalogue-number-completeness')!;
      expect(check.passed).toBe(true);
    });

    // ── Format-aware completeness (2026-08-28) ────────────────────────────
    // The gapless-1..N sequence check runs for every format (NFC dogs
    // consume numbers regardless), but which entryNames must be FOUND in
    // the rendered text depends on the contract — see resolvePreflightContract.

    it('judging: an NFC entry that is never drawn does not fail completeness — the detail names the exclusion', async () => {
      const pdf = await buildFixtureWithUndrawnNfc();
      const report = await runCataloguePreflight(pdf, nfcSnapshot(), { format: 'judging' });
      const check = report.checks.find((c) => c.id === 'catalogue-number-completeness')!;
      expect(check.passed, check.detail).toBe(true);
      expect(check.detail).toContain('1 NFC entries (#5) are not printed in this format by design');
    });

    it('standard: the SAME undrawn NFC entry fails completeness — standard prints every entry, including NFC', async () => {
      const pdf = await buildFixtureWithUndrawnNfc();
      const report = await runCataloguePreflight(pdf, nfcSnapshot(), { format: 'standard' });
      const check = report.checks.find((c) => c.id === 'catalogue-number-completeness')!;
      expect(check.passed).toBe(false);
      expect(check.detail).toContain('GHOST NFC DOG');
      expect(report.passed).toBe(false);
    });

    it('absentees: names are not checked at all — passes even though none of the "entry names" were drawn', async () => {
      const pdf = await buildFixtureWithUndrawnNfc(); // draws "DOG NUMBER 1".."DOG NUMBER 4"
      const report = await runCataloguePreflight(
        pdf,
        baseSnapshot({
          expectedNumbers: [1, 2, 3, 4],
          entryNames: [1, 2, 3, 4].map((n) => ({ number: n, name: `NEVER PRINTED NAME ${n}` })),
        }),
        { format: 'absentees' },
      );
      const check = report.checks.find((c) => c.id === 'catalogue-number-completeness')!;
      expect(check.passed, check.detail).toBe(true);
      expect(check.detail).toContain('entry names not checked — an absentee list is a subset of the entries by definition');
      expect(report.contract.binding).toBe('loose');
    });

    it('by-class + WUSV: an undrawn NFC entry passes, and the detail carries the "regionals allow no NFC" note', async () => {
      const pdf = await buildFixtureWithUndrawnNfc();
      const report = await runCataloguePreflight(pdf, nfcSnapshot({ showRuleset: 'wusv' }), { format: 'by-class' });
      const check = report.checks.find((c) => c.id === 'catalogue-number-completeness')!;
      expect(check.passed, check.detail).toBe(true);
      expect(check.detail).toContain('regionals allow no NFC entries and the SV catalogue does not print them');
    });

    it('by-class + RKC: the SAME undrawn NFC entry fails — non-WUSV by-class prints every entry, including NFC', async () => {
      const pdf = await buildFixtureWithUndrawnNfc();
      const report = await runCataloguePreflight(pdf, nfcSnapshot({ showRuleset: 'rkc' }), { format: 'by-class' });
      const check = report.checks.find((c) => c.id === 'catalogue-number-completeness')!;
      expect(check.passed).toBe(false);
      expect(check.detail).toContain('GHOST NFC DOG');
    });

    it('folds a curly apostrophe against pdftotext rendering it as a space (Scotland regional #52, job 99012c37)', async () => {
      const doc = await PDFDocument.create();
      const font = await embeddedInterFont(doc);
      const page = doc.addPage(A5 as unknown as [number, number]);
      // What pdftotext -layout actually emitted for this Inter subset:
      // the U+2019 apostrophe extracts as a bare space.
      drawEntryPage(page, font, ['1  CH SADIRA S YOKKO FOR ELLROOST']);

      const pdf = Buffer.from(await doc.save());
      const report = await runCataloguePreflight(
        pdf,
        baseSnapshot({
          expectedNumbers: [1],
          entryNames: [{ number: 1, name: 'CH SADIRA’S YOKKO FOR ELLROOST ' }],
        }),
        { format: 'standard' },
      );
      const check = report.checks.find((c) => c.id === 'catalogue-number-completeness')!;
      expect(check.passed, check.detail).toBe(true);
    });

    it('finds a name wrapped inside one two-column cell via -raw, where -layout interleaves it with the other column', async () => {
      const pdf = await buildTwoColumnWrapFixture();
      const report = await runCataloguePreflight(
        pdf,
        baseSnapshot({
          expectedNumbers: [1, 2],
          entryNames: [
            { number: 1, name: 'AMIRA VOM FICHTENSCHLAG (IMP DEU)' },
            { number: 2, name: 'OTHER DOG' },
          ],
        }),
        { format: 'standard' },
      );
      const check = report.checks.find((c) => c.id === 'catalogue-number-completeness')!;
      expect(check.passed, check.detail).toBe(true);
      expect(check.detail).not.toContain('AMIRA VOM FICHTENSCHLAG');
    });
  });

  describe('page-count-booklet / page-count-loose (format-aware binding)', () => {
    it('fails on a 3-page document (not a multiple of 4)', async () => {
      const pdf = await buildFixture(3);
      const report = await runCataloguePreflight(
        pdf,
        baseSnapshot({ expectedNumbers: [1, 2, 3], entryNames: [1, 2, 3].map((n) => ({ number: n, name: `DOG NUMBER ${n}` })) }),
        { format: 'standard' },
      );
      const check = report.checks.find((c) => c.id === 'page-count-booklet')!;
      expect(check.passed).toBe(false);
      expect(report.artefact.pages).toBe(3);
      expect(report.passed).toBe(false);
    });

    it('passes on a 4-page document', async () => {
      const pdf = await buildWellFormedFixture();
      const report = await runCataloguePreflight(pdf, baseSnapshot(), { format: 'standard' });
      const check = report.checks.find((c) => c.id === 'page-count-booklet')!;
      expect(check.passed).toBe(true);
    });

    // ── (a) judging, 5 pages: loose binding, not booklet ──────────────────
    it('judging: a 5-page (non-multiple-of-4) steward book is NOT held to the booklet rule', async () => {
      const pdf = await buildFixture(5);
      const snapshot = baseSnapshot({
        expectedNumbers: [1, 2, 3, 4, 5],
        entryNames: [1, 2, 3, 4, 5].map((n) => ({ number: n, name: `DOG NUMBER ${n}` })),
      });
      const report = await runCataloguePreflight(pdf, snapshot, { format: 'judging' });

      expect(report.contract.binding).toBe('loose');
      const loose = report.checks.find((c) => c.id === 'page-count-loose');
      expect(loose).toBeDefined();
      expect(loose!.passed, loose!.detail).toBe(true);
      expect(report.checks.find((c) => c.id === 'page-count-booklet')).toBeUndefined();
      expect(report.passed, JSON.stringify(report.checks)).toBe(true);
    });

    // ── (b) same 5-page count, requested as standard: booklet fails ───────
    it('standard: the SAME 5-page count fails page-count-booklet (unchanged truth for the actual booklet format)', async () => {
      const pdf = await buildFixture(5);
      const snapshot = baseSnapshot({
        expectedNumbers: [1, 2, 3, 4, 5],
        entryNames: [1, 2, 3, 4, 5].map((n) => ({ number: n, name: `DOG NUMBER ${n}` })),
      });
      const report = await runCataloguePreflight(pdf, snapshot, { format: 'standard' });

      expect(report.contract.binding).toBe('booklet');
      const booklet = report.checks.find((c) => c.id === 'page-count-booklet');
      expect(booklet).toBeDefined();
      expect(booklet!.passed).toBe(false);
      expect(report.checks.find((c) => c.id === 'page-count-loose')).toBeUndefined();
      expect(report.passed).toBe(false);
    });
  });

  describe('fonts-embedded', () => {
    it('fails on a document using an unembedded base-14 font', async () => {
      const pdf = await buildFixture(4, { useBase14: true });
      const report = await runCataloguePreflight(
        pdf,
        baseSnapshot({ expectedNumbers: [1, 2, 3, 4], entryNames: [1, 2, 3, 4].map((n) => ({ number: n, name: `DOG NUMBER ${n}` })) }),
        { format: 'standard' },
      );
      const check = report.checks.find((c) => c.id === 'fonts-embedded')!;
      expect(check.passed).toBe(false);
      expect(check.detail).toMatch(/helvetica/i);
      expect(report.passed).toBe(false);
    });

    it('passes on a document with an embedded (subsetted) font', async () => {
      const pdf = await buildWellFormedFixture();
      const report = await runCataloguePreflight(pdf, baseSnapshot(), { format: 'standard' });
      const check = report.checks.find((c) => c.id === 'fonts-embedded')!;
      expect(check.passed).toBe(true);
    });
  });

  describe('no-blank-pages', () => {
    it('fails when one page is genuinely blank', async () => {
      const pdf = await buildFixture(4, { blankPageIndex: 1 });
      const report = await runCataloguePreflight(
        pdf,
        baseSnapshot({ expectedNumbers: [1, 2, 3, 4], entryNames: [1, 2, 3, 4].map((n) => ({ number: n, name: `DOG NUMBER ${n}` })) }),
        { format: 'standard' },
      );
      const check = report.checks.find((c) => c.id === 'no-blank-pages')!;
      expect(check.passed).toBe(false);
      expect(check.detail).toMatch(/position\(s\) 2/);
      expect(report.passed).toBe(false);
    });

    it('does NOT flag a ruled Notes-style padding page as blank', async () => {
      const pdf = await buildFixtureWithNotesPage();
      const report = await runCataloguePreflight(
        pdf,
        baseSnapshot({
          expectedNumbers: [1, 2, 3],
          entryNames: [
            { number: 1, name: 'FIDO OF SOMEWHERE' },
            { number: 2, name: 'REX OF ELSEWHERE' },
            { number: 3, name: 'BELLA OF NOWHERE' },
          ],
        }),
        { format: 'standard' },
      );
      const check = report.checks.find((c) => c.id === 'no-blank-pages')!;
      expect(check.passed, check.detail).toBe(true);
    });

    it('passes a fully populated 4-page document', async () => {
      const pdf = await buildWellFormedFixture();
      const report = await runCataloguePreflight(pdf, baseSnapshot(), { format: 'standard' });
      const check = report.checks.find((c) => c.id === 'no-blank-pages')!;
      expect(check.passed).toBe(true);
    });
  });

  describe('rkc-wording (warn only)', () => {
    it('warns, but does not fail the report, when standalone "KC" appears', async () => {
      const doc = await PDFDocument.create();
      const font = await embeddedInterFont(doc);
      const p1 = doc.addPage(A5 as unknown as [number, number]);
      drawEntryPage(p1, font, ['1  FIDO OF SOMEWHERE', 'Judge: A Person (KC A-List)']);
      for (let i = 1; i < 4; i++) {
        const p = doc.addPage(A5 as unknown as [number, number]);
        drawEntryPage(p, font, [`${i + 1}  DOG NUMBER ${i + 1}`]);
      }
      const pdf = Buffer.from(await doc.save());
      const report = await runCataloguePreflight(
        pdf,
        baseSnapshot({ expectedNumbers: [1, 2, 3, 4], entryNames: [{ number: 1, name: 'FIDO OF SOMEWHERE' }, ...[2, 3, 4].map((n) => ({ number: n, name: `DOG NUMBER ${n}` }))] }),
        { format: 'standard' },
      );
      const check = report.checks.find((c) => c.id === 'rkc-wording')!;
      expect(check.level).toBe('warn');
      expect(check.passed).toBe(false);
      // A warn-level failure must never flip the overall report to failed.
      expect(report.passed).toBe(true);
    });

    it('does not false-positive on "RKC" itself', async () => {
      const pdf = await buildWellFormedFixture();
      const report = await runCataloguePreflight(pdf, baseSnapshot(), { format: 'standard' });
      const check = report.checks.find((c) => c.id === 'rkc-wording')!;
      expect(check.passed).toBe(true);
    });
  });

  describe('stable-identity', () => {
    it('warns (not fails) when rendererGitSha is explicitly null', async () => {
      const pdf = await buildWellFormedFixture();
      const report = await runCataloguePreflight(pdf, baseSnapshot({ rendererGitSha: null }), { format: 'standard' });
      const check = report.checks.find((c) => c.id === 'stable-identity')!;
      expect(check.level).toBe('warn');
      expect(check.passed).toBe(true);
      expect(report.passed).toBe(true);
    });

    it('passes at fail-level when rendererGitSha is recorded', async () => {
      const pdf = await buildWellFormedFixture();
      const report = await runCataloguePreflight(pdf, baseSnapshot({ rendererGitSha: 'deadbeef' }), { format: 'standard' });
      const check = report.checks.find((c) => c.id === 'stable-identity')!;
      expect(check.level).toBe('fail');
      expect(check.passed).toBe(true);
    });
  });

  it('produces a JSON-serialisable report that carries the format contract', async () => {
    const pdf = await buildWellFormedFixture();
    const report = await runCataloguePreflight(pdf, baseSnapshot(), { format: 'standard' });
    expect(() => JSON.stringify(report)).not.toThrow();
    const roundTripped = JSON.parse(JSON.stringify(report));
    expect(roundTripped.passed).toBe(report.passed);
    expect(roundTripped.checks).toHaveLength(report.checks.length);
    expect(roundTripped.contract).toEqual(report.contract);
    expect(report.contract).toMatchObject({
      format: 'standard',
      effectiveFormat: 'standard',
      binding: 'booklet',
      completeness: 'all',
    });
    expect(typeof report.contract.label).toBe('string');
    expect(typeof report.contract.rationale).toBe('string');
  });
});
